StudyBud/config/routes.rb
Rails.application.routes.draw do

  root 'cards#index'

  resources :cards
  resources :decks

end

StudyBud/app/models/card.rb
class Card < ActiveRecord::Base
	# belongs_to :deck
	# validates :deck, presence: true

	def self.random 
        @cards = Card.all
        @card_random = @cards.shuffle.first
        return @card_random
  end

  def self.eql?
  	@card = Card.find(params[:id])
  	if @card.answer.downcase == params [:answer].downcase
  		@answer = "Correct"
  	else
  		@answer = "Nope. Try again."
  	end
  end

end

StudyBud/app/models/deck.rb
class Deck < ActiveRecord::Base
	# belongs_to :user
	# has_many :cards
	# has_many :games
	
end

StudyBud/app/models/game.rb
# class Game < ActiveRecord::Base
# 	belongs_to :deck
# 	belongs_to :user
# 	# validates :user, presence: true
# 	# validates :deck, presence: true

# end

StudyBud/app/models/user.rb
class User < ActiveRecord::Base
	has_many :decks, dependent: :destroy
	has_many :games, dependence: :destroy
end

StudyBud/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

StudyBud/app/controllers/cards_controller.rb
class CardsController < ApplicationController

	def index
		@cards = Card.all
		@card_shuffle = Card.random
		# @answer = Card.eql?
	end

	def show
		@card = Card.find(params[:id])
	end

	def new 
		@card = Card.new
	end

	def create
		@card = Card.new( card_params )
		if @card.save
			redirect_to @card
		else
			render :new
		end
	end

	def edit
    @card = Card.find(params[:id])
  end

  def answer
  	@answer
  end

  def update
    @card = Card.find(params[:id])
    @card.update(card_params)
    redirect_to @card
  end

  def destroy
  	find_card
     @card.destroy
     redirect_to cards_path
  end

private

  def card_params
    params.require(:card).permit(:question, :answer)
  end

  def find_card
    @card = Card.find(params[:id])
  end

end

StudyBud/app/controllers/decks_controller.rb
class DecksController < ApplicationController


end

StudyBud/app/controllers/games_controller.rb
class GamesController < ApplicationController

def play Games
end

end

StudyBud/app/controllers/users_controller.rb
class UsersController < ApplicationController



end

StudyBud/app/helpers/application_helper.rb
module ApplicationHelper
end

StudyBud/app/views/cards/_form.html.erb
<% if @card.errors.any? %>
<ul>
	<% @card.errors.full_messages.each do |err| %>
	<li><%= err %></li>
	<% end %>
</ul>
<% end %>


<%= form_for @card do |c| %> 

	<%= c.label :question %> 
	<%= c.text_field :question %> 

	<%= c.label :answer %>
	<%= c.text_area :answer %>

	<%= c.submit %>

<% end %>

StudyBud/app/views/cards/answer.html.erb
<%=@answer%>

StudyBud/app/views/cards/card.html.erb
<%= form_for @card do |c| %> 
<!-- 
	<%= c.label :deck %>
	<%= c.text_field :deck %> -->

	<%= c.label :question %> 
	<%= c.text_field :question %> 

	<%= c.label :answer %>
	<%= c.text_field :answer %>

	<%= c.submit %>

<% end %>

StudyBud/app/views/cards/edit.html.erb
<h2>Edit Your Card</h2>
<%= render 'form' %>

StudyBud/app/views/cards/index.html.erb
<h2>Cards Cards Cards</h2>

<ul>
	<h1><%= @card_shuffle.question %></h1>

	<%= form_for [@card, @card.answer] do |c| %>
	<%= c.label :answer %>
	<%= c.text_field :answer %>
<!-- 
	<%= f.submit %> -->
	<%= link_to "Get the Answer", card_path (card) %>

	<% end %>
	
	<li><%= link_to "Create a Card", new_card_path %></li> 
<% @cards.each do |card| %>
  <li> <%= link_to card.question, card_path(card) %></li>
<% end %>
</ul>

StudyBud/app/views/cards/new.html.erb
<%= render 'form' %>

StudyBud/app/views/cards/show.html.erb
<h2><%= @card.question %></h2>
<p><%= @card.answer %></p>
<p><%= @answer %></p>
<br>

<%= link_to 'Edit the Question', edit_card_path(@card) %>
<br></br>
<%= link_to 'Delete the Question', card_path(@card), method: :delete %>
<br></br>
<%= link_to 'Go Back to the Homepage', cards_path %>

StudyBud/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StudyBud</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>